"""adding cart

Revision ID: b582190f2636
Revises: 2926ed772ff4
Create Date: 2023-08-03 08:16:54.029501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b582190f2636'
down_revision = '2926ed772ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=15), nullable=False),
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=15), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Pid'], ['prod.id'], name='fkpid'),
    sa.ForeignKeyConstraint(['pname'], ['prod.pname'], name='fkp'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_cart_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
