"""empty message

Revision ID: c1fdd6388098
Revises: e91d3159b1a4
Create Date: 2023-08-12 18:14:49.122903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fdd6388098'
down_revision = 'e91d3159b1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('_uname_role_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('_uname_role_uc', ['uname', 'role'])

    # ### end Alembic commands ###
