"""adding qty to cart

Revision ID: d594838bcd76
Revises: 8f9ccd3e3623
Create Date: 2023-08-03 22:22:32.583844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd594838bcd76'
down_revision = '8f9ccd3e3623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('no')

    # ### end Alembic commands ###
