"""added offers

Revision ID: f2eccb04c033
Revises: f4992662d517
Create Date: 2023-08-04 22:37:49.214955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2eccb04c033'
down_revision = 'f4992662d517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod', schema=None) as batch_op:
        batch_op.drop_column('offer')

    # ### end Alembic commands ###
